reside-eng/workflow-templates-library

.github/workflows/verify_library.yml

fix: switch to non prod slack channel to reduce noise

---

.github/actions/playwright/action.yml

fix: support local Inter.zip for playwright

---

.github/workflows/verify_library.yml

:tickets: CORE-13167 
https://github.com/reside-eng/pantry/pull/2075
Skip Storybook/Percy for PRs which are draft or are created by renovate (dep updates)

feat: skip percy for dep and draft PRs [CORE-13167]

---

.github/workflows/release_library.yml

fix: release_library

---

.github/workflows/release_library.yml

I mistakenly replaced publish tokens with read tokens during the refactor. This PR reverts that change and uses publish tokens.

fix: use proper token

---

.github/workflows/release_library.yml

fix: make NPM tokens available to whole release job

---

.github/actions/storybook/action.yml
.github/workflows/verify_library.yml

:tickets: TICKET-000 
Create preview url for draft PRs while still skipping Percy for draft and renovate PRs - this was per request: https://top-agent.slack.com/archives/C02S7T34ZHR/p1724858084769979

fix: create preview for draft PRs

---

.github/workflows/release_library.yml
.github/workflows/verify_library.yml
README.md

fix: remove not needed inputs

---

.github/workflows/release_library.yml
.github/workflows/verify_library.yml
README.md

fix: cleanup unneeded secrets + update default slack channel

---

.github/workflows/check-nodejs-dependencies.yml
.github/workflows/release_library.yml

feat: add dep stats workflow

---

.github/workflows/release_library.yml

fix: unify semantic-action version and to fix secondary rate limit issue

---

.github/workflows/check-nodejs-dependencies.yml
.github/workflows/release_library.yml
.github/workflows/verify_library.yml

This PR needs to be merged first: https://github.com/reside-eng/terraform/pull/1305
:tickets: TICKET-000

feat: remove coverall upload + upload summary to Cloud Storage

---

.github/workflows/check-nodejs-dependencies.yml
.github/workflows/release_library.yml
.github/workflows/verify_library.yml

Reverts reside-eng/workflow-templates-library#88

fix: Revert "feat: remove coverall upload + upload summary to Cloud Storage"

---

.github/workflows/release_library.yml

feat: skip percy for renovate

---

.github/workflows/release_library.yml

* Add support for conventional commits
https://github.com/reside-eng/workflow-templates/pull/757

feat: add support for conventional commits

---

.github/workflows/verify_library.yml

fix: increase verify timeout to 30m

---

.github/actions/ci-analytics/action.yml
.github/workflows/check-nodejs-dependencies.yml
.github/workflows/release_library.yml
.github/workflows/verify_library.yml

fix: reference to workflow-templates for public libraries

---

.github/workflows/check-nodejs-dependencies.yml
.github/workflows/release_library.yml
.github/workflows/verify_library.yml

fix: revert ci analytics

---

.github/workflows/check-nodejs-dependencies.yml
.github/workflows/release_library.yml

:tickets: TICKET-000 
Support monorepos
Tested in test-monorepo

feat: support monorepos [PLAT-8693]

---

.github/actions/ci-analytics/action.yml
.github/workflows/check-nodejs-dependencies.yml
.github/workflows/release_library.yml
.github/workflows/verify_library.yml

Require this PR to be merged first: https://github.com/reside-eng/workflow-ci-analytics-action/pull/20
:tickets: TICKET-000

feat: add CI analytics

---

.github/workflows/release_library.yml

Requiring this [PR](https://github.com/reside-eng/workflow-status-notification-action/pull/941) to be merged first.
:tickets: TICKET-000

feat: add notification for every release failures

---

.github/workflows/release_library.yml

:tickets: TICKET-000 
Rename input for enabling/disabling dependency check to match existing input naming

fix: switch to ENABLE_* naming for dep check input

---

.github/workflows/publish.yml

fix: update status notification action to v1

---

.github/workflows/release_library.yml
.github/workflows/verify_library.yml

fix: add TEST_NODE_OPTIONS with 4gb default memory
